input: ["source"]
output: ["img"]

resize: {
            do_resizing: False,
            width: 1280,
            height: 720
        }
input_source: 0    # 0 for webcam, rtsp URL for CCTV
mirror_image: False