input: ["img", "masks", "bbox_labels", "bbox_scores"]
output: ["img"]

instance_color_scheme: hue_family

effect: {
  standard_mask: True,
  brightness: None,
  contrast: None,
  gamma_correction: None,
  blur: None,
  mosaic: None
}
effect_area: masked

contours: {
    show: False,
    thickness: 2
}
