input: ["img", "masks", "bbox_labels", "bbox_scores"]
output: ["img"]

instance_color_scheme: hue_family

effect: null
effect_area: masked

gamma: 1.0
alpha: 1.0
beta: 0
blur_kernel_size: 50
mosaic_level: 25

show_contours: False
contour_thickness: 2