name: Code Check
on: [push, pull_request]

jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check for copyright and license headers in .py files
        run: bash ./scripts/check_headers.sh
      - name: Run Bandit Linter
        run: bash ./scripts/bandit.sh
      - name: Run linter
        run: bash ./scripts/linter.sh
      - name: Run type checker
        run: bash ./scripts/check_type.sh
      - name: Run unit tests
        run: bash ./scripts/run_tests.sh unit

