name: ML Model Tests
on: 
  push:
    branches:
      - main
      - dev

jobs:
  unit_test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run MLModel tests
        run: bash ./scripts/run_tests.sh mlmodel
